const TiposErrores = {
    
    ERROR_AL_CREAR_PRODUCTO: 'ERROR_AL_CREAR_PRODUCTO',
    USUARIO_NO_EXISTE:'USUARIO_NO_EXISTE',
    ERROR_SERVIDOR_INTERNO:'ERROR_SERVIDOR_INTERNO',
    NO_AUTORIZADO: 'NO_AUTORIZADO',
    PRODUCTO_NO_ENCONTRADO: 'PRODUCTO_NO_ENCONTRADO'
}

module.exports = TiposErrores
