const TiposErrores = {
    
    PRODUCT_CREATION_ERROR: 'PRODUCT CREATION ERROR',
    USER_NOT_EXIST:'USER NOT EXIST',
    INTERNAL_SERVER_ERROR:'INTERNAL SERVER ERROR',
    NOT_AUTHORIZED: 'USER NOT AUTHORIZED',
    PRODUCT_NOT_FOUND: 'PRODUCT NOT FOUND'
}

module.exports = TiposErrores
